check_times:
  cron: "0,15,30,45 * * * *"
  class: CheckTime
  queue: availability
  description: "test"

resque_canary:
  cron: "0 * * * *"
  class: ResqueCanary
  queue: availability
  description: "make sure resque and redis are running properly"

clear_old_times:
  cron: "0 0 * * *"
  class: ClearOldTimes
  queue: availability
  description: "clear checks of times that are in the past"
