check_times:
  cron: "0,15,30,45 * * * *"
  class: CheckTime
  queue: availability
  description: "test"

clear_old_times:
  cron: "0 0 * * *"
  class: ClearOldTimes
  queue: availability
  description: "clear checks of times that are in the past"
